//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LQModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DroitAcces
    {
        public string UtilisateursLogin { get; set; }
        public int EvenementEvenementId { get; set; }
        public int EvenementCentreCentreId { get; set; }
        public int Niveau { get; set; }
    
        public virtual Evenement Evenement { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
