//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LQModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evenement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evenement()
        {
            this.DroitAcces = new HashSet<DroitAcces>();
            this.ScoreCard = new HashSet<ScoreCard>();
        }
    
        public int EvenementId { get; set; }
        public string Nom { get; set; }
        public int CentreCentreId { get; set; }
        public string Description { get; set; }
        public int TypeAcces { get; set; }
        public typeEvenement TypeEvenement { get; set; }
        public Nullable<int> ScoringSysteme_ScoringSystemeId { get; set; }
    
        public virtual Centre Centre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DroitAcces> DroitAcces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreCard> ScoreCard { get; set; }
        public virtual ScoringSysteme ScoringSysteme { get; set; }
    }
}
