//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LQModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LQDMEntities : DbContext
    {
        public LQDMEntities()
            : base("name=LQDMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Centre> Centre { get; set; }
        public virtual DbSet<DroitAcces> DroitAcces { get; set; }
        public virtual DbSet<Evenement> Evenement { get; set; }
        public virtual DbSet<LigneScore> LigneScore { get; set; }
        public virtual DbSet<ScoreCard> ScoreCard { get; set; }
        public virtual DbSet<ScoringSysteme> ScoringSysteme { get; set; }
        public virtual DbSet<Utilisateurs> Utilisateurs { get; set; }
    }
}
