//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LQModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoringSysteme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScoringSysteme()
        {
            this.Evenement = new HashSet<Evenement>();
        }
    
        public int ScoringSystemeId { get; set; }
        public string Nom { get; set; }
        public int ratioMax { get; set; }
        public int ratioPts { get; set; }
        public int frontPlus { get; set; }
        public int backPlus { get; set; }
        public int gunPlus { get; set; }
        public int shoulderPlus { get; set; }
        public int frontMoins { get; set; }
        public int backMoins { get; set; }
        public int gunMoins { get; set; }
        public int shoulderMoins { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evenement> Evenement { get; set; }
    }
}
